### PR TITLE
Mg branch

### PR DESCRIPTION
**Pull request by mgratti**
step3*py:
- removed miniaod and other useless stuff
- added option to run reference values of seeding, gathering, pfrechit thresholds

prodHelper.py
- now possible to run either flat energy or flat pt

postProdHelper.py
- added script to create a list with the files that need to be run with the dumper and an example command

updated workflow for cmssw development 
updated workflow for running the dumper

### CODE REVIEW

**Comment by mgratti** [comment]
@amlyon

**Comment by amlyon** [comment]
Hi Maria Giulia,

Thanks a lot for your PR and the nice improvements!

So if I understand properly, in order to get the modifications on the EDProducer, one has now to merge your topic as well?

@mgratti

**Comment by mgratti** [comment]
Actually Badder just merged my PR with latest modifications under the PR_ParticleGuns topic.
So at this point, my topic is not needed.

**Comment by amlyon** [comment]
Ok!

And then would you suggest to merge systematically the three topics of 
Badder?

Le 24.10.2019 14:46, Maria Giulia Ratti a écrit :
> Actually Badder just merged my PR with latest modifications under the
> PR_ParticleGuns topic.
> So at this point, my topic is not needed.
>

**Comment by mgratti** [comment]
Yes, the three topics under badder repo are enough to get all needed modifications to cmssw

**Comment by amlyon** [comment]
Ok!

I don't have further questions, should I proceed to the merging?

Le 24.10.2019 14:55, Maria Giulia Ratti a écrit :
> Yes, the three topics under badder repo are enough to get all needed
> modifications to cmssw
>

**Comment by mgratti** [comment]
I would say so, thanks!

**Pull request merged**
