### PR TITLE
Importation of Badder's modifications on the Dumper

### PR DESCRIPTION
**Pull request by amlyon**
In this PR:

- changes from Badder first pulled on am-branch and now imported to the master

- in prodHelper.py: 
    - made it possible to have min energy at the MeV scale
    - added to the batch command --account=cn-test  in order to be able to run
      @mgratti  Please check that you can still submit jobs with this command!

### CODE REVIEW

**Comment by mgratti** [comment]
ok, I will check now

**Comment by mgratti** [comment]
For the submission of jobs, I can still run no problem, @amlyon.

As for Badder's modifications, it's hard to go through them by eye.
I notice that changes to the cfg files  should be propagated  to our Cfg_[] as well.

Before merging to the master, the changes should be tested though (especially in this case where many things changed), otherwise we break the master, which we don't want to do :)

**Comment by amlyon** [comment]
@mgratti The new version has been tested on both EE and EB files, and it works fine

**Comment by mgratti** [comment]
Sorry for the delay, I forgot to merge yesterday.
Now it's merged

**Pull request merged**
