### PR TITLE
Am branch

### PR DESCRIPTION
**Pull request by amlyon**
@mgratti 

The main changes imported by the PR are:

- QCD production enabled:
    -> standalone step1 created (to respect the logic of having an individual step1 for the different cases)
    -> step3 modified: now can also produced miniaod 
    -> step4 created: miniaoadsim -> nanoaodsim
    At the level of the prodHelper: 
         -> --ch QCD to switch to QCD prod
         -> this will switch on automatically the --dominiaodfile and off --dorecofile
         -> will not run the dumper and run the step4 instead

- Handling of the safety margin: 
     -> the 10% safety margin on the values of the thresholds is now removed by default, and can be reactivated with --dosafetymargin

 - Specification of the year of the noise condition:
      -> now possible to produce sample with GT of year X and noise conditions of year Y
      -> for that, --noiseCond Y has to be added to the command line

- Now possible to produce reco samples with different sigma multiplicities below and above eta=2.5
      -> for that, use --pfrhmultbelow2p5 X --pfrhmultabove2p5 Y instead of --pfrhmult Z
      -> same for seeding
      -> always possibility to use --dopfrhmult --doseedmult if one wants same thresholds for all eta

### CODE REVIEW

**Comment by mgratti** [comment]
I have a question, @amlyon ; it does not need to be addressed now.
I remember that in his step3 Badder added the MET filters as branches to be added in the miniAOD. I think it could be helpful for the future if we have to look at data.
Can you double check with Badder?

**Comment by mgratti** [comment]
@amlyon, let me add that the term "noisecond" is a bit of a misname, because the noise is not actually changed, the thresholds are; the actual noise conditions are still specified in the year.

**Comment by amlyon** [comment]
I see your point. To my mind, the thresholds are anyway set wrt the 
noise, which led to that name, but I am happy to change it to something 
that you find more suitable

Le 09.03.2020 17:42, Maria Giulia Ratti a écrit :
> @amlyon, let me add that the term "noisecond" is a bit of a misname,
> because the noise is not actually changed, the thresholds are; the
> actual noise conditions are still specified in the year.

**Comment by mgratti** [comment]
for me it’s fine to keep it this way. just wanted to keep the conceptual difference in mind

**Pull request merged**
